import 'package:youpass/core/models/country_code.dart';

class CountryCodesData {
  CountryCodesData._();

  static const String defaultPhoneHint = '123 456 7890';

  static const List<CountryCode> all = [
    CountryCode(
      name: 'Chile',
      isoCode: 'CL',
      dialCode: '56',
      flagEmoji: '🇨🇱',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Afghanistan',
      isoCode: 'AF',
      dialCode: '93',
      flagEmoji: '🇦🇫',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Aland Islands',
      isoCode: 'AX',
      dialCode: '358',
      flagEmoji: '🇦🇽',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Albania',
      isoCode: 'AL',
      dialCode: '355',
      flagEmoji: '🇦🇱',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Algeria',
      isoCode: 'DZ',
      dialCode: '213',
      flagEmoji: '🇩🇿',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'American Samoa',
      isoCode: 'AS',
      dialCode: '1',
      flagEmoji: '🇦🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Andorra',
      isoCode: 'AD',
      dialCode: '376',
      flagEmoji: '🇦🇩',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Angola',
      isoCode: 'AO',
      dialCode: '244',
      flagEmoji: '🇦🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Anguilla',
      isoCode: 'AI',
      dialCode: '1',
      flagEmoji: '🇦🇮',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Antarctica',
      isoCode: 'AQ',
      dialCode: '672',
      flagEmoji: '🇦🇶',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Antigua and Barbuda',
      isoCode: 'AG',
      dialCode: '1',
      flagEmoji: '🇦🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Argentina',
      isoCode: 'AR',
      dialCode: '54',
      flagEmoji: '🇦🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Armenia',
      isoCode: 'AM',
      dialCode: '374',
      flagEmoji: '🇦🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Aruba',
      isoCode: 'AW',
      dialCode: '297',
      flagEmoji: '🇦🇼',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Australia',
      isoCode: 'AU',
      dialCode: '61',
      flagEmoji: '🇦🇺',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Austria',
      isoCode: 'AT',
      dialCode: '43',
      flagEmoji: '🇦🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Azerbaijan',
      isoCode: 'AZ',
      dialCode: '994',
      flagEmoji: '🇦🇿',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Bahrain',
      isoCode: 'BH',
      dialCode: '973',
      flagEmoji: '🇧🇭',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Bangladesh',
      isoCode: 'BD',
      dialCode: '880',
      flagEmoji: '🇧🇩',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Barbados',
      isoCode: 'BB',
      dialCode: '1',
      flagEmoji: '🇧🇧',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Belarus',
      isoCode: 'BY',
      dialCode: '375',
      flagEmoji: '🇧🇾',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Belgium',
      isoCode: 'BE',
      dialCode: '32',
      flagEmoji: '🇧🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Belize',
      isoCode: 'BZ',
      dialCode: '501',
      flagEmoji: '🇧🇿',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Benin',
      isoCode: 'BJ',
      dialCode: '229',
      flagEmoji: '🇧🇯',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Bermuda',
      isoCode: 'BM',
      dialCode: '1',
      flagEmoji: '🇧🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Bhutan',
      isoCode: 'BT',
      dialCode: '975',
      flagEmoji: '🇧🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Bolivia',
      isoCode: 'BO',
      dialCode: '591',
      flagEmoji: '🇧🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Bonaire, Sint Eustatius and Saba',
      isoCode: 'BQ',
      dialCode: '599',
      flagEmoji: '🇧🇶',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Bosnia and Herzegovina',
      isoCode: 'BA',
      dialCode: '387',
      flagEmoji: '🇧🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Botswana',
      isoCode: 'BW',
      dialCode: '267',
      flagEmoji: '🇧🇼',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Bouvet Island',
      isoCode: 'BV',
      dialCode: '0055',
      flagEmoji: '🇧🇻',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Brazil',
      isoCode: 'BR',
      dialCode: '55',
      flagEmoji: '🇧🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'British Indian Ocean Territory',
      isoCode: 'IO',
      dialCode: '246',
      flagEmoji: '🇮🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Brunei',
      isoCode: 'BN',
      dialCode: '673',
      flagEmoji: '🇧🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Bulgaria',
      isoCode: 'BG',
      dialCode: '359',
      flagEmoji: '🇧🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Burkina Faso',
      isoCode: 'BF',
      dialCode: '226',
      flagEmoji: '🇧🇫',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Burundi',
      isoCode: 'BI',
      dialCode: '257',
      flagEmoji: '🇧🇮',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Cambodia',
      isoCode: 'KH',
      dialCode: '855',
      flagEmoji: '🇰🇭',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Cameroon',
      isoCode: 'CM',
      dialCode: '237',
      flagEmoji: '🇨🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Canada',
      isoCode: 'CA',
      dialCode: '1',
      flagEmoji: '🇨🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Cape Verde',
      isoCode: 'CV',
      dialCode: '238',
      flagEmoji: '🇨🇻',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Cayman Islands',
      isoCode: 'KY',
      dialCode: '1',
      flagEmoji: '🇰🇾',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Central African Republic',
      isoCode: 'CF',
      dialCode: '236',
      flagEmoji: '🇨🇫',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Chad',
      isoCode: 'TD',
      dialCode: '235',
      flagEmoji: '🇹🇩',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'China',
      isoCode: 'CN',
      dialCode: '86',
      flagEmoji: '🇨🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Christmas Island',
      isoCode: 'CX',
      dialCode: '61',
      flagEmoji: '🇨🇽',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Cocos (Keeling) Islands',
      isoCode: 'CC',
      dialCode: '61',
      flagEmoji: '🇨🇨',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Colombia',
      isoCode: 'CO',
      dialCode: '57',
      flagEmoji: '🇨🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Comoros',
      isoCode: 'KM',
      dialCode: '269',
      flagEmoji: '🇰🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Congo',
      isoCode: 'CG',
      dialCode: '242',
      flagEmoji: '🇨🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Cook Islands',
      isoCode: 'CK',
      dialCode: '682',
      flagEmoji: '🇨🇰',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Costa Rica',
      isoCode: 'CR',
      dialCode: '506',
      flagEmoji: '🇨🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Croatia',
      isoCode: 'HR',
      dialCode: '385',
      flagEmoji: '🇭🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Cuba',
      isoCode: 'CU',
      dialCode: '53',
      flagEmoji: '🇨🇺',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Curaçao',
      isoCode: 'CW',
      dialCode: '599',
      flagEmoji: '🇨🇼',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Cyprus',
      isoCode: 'CY',
      dialCode: '357',
      flagEmoji: '🇨🇾',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Czech Republic',
      isoCode: 'CZ',
      dialCode: '420',
      flagEmoji: '🇨🇿',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Democratic Republic of the Congo',
      isoCode: 'CD',
      dialCode: '243',
      flagEmoji: '🇨🇩',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Denmark',
      isoCode: 'DK',
      dialCode: '45',
      flagEmoji: '🇩🇰',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Djibouti',
      isoCode: 'DJ',
      dialCode: '253',
      flagEmoji: '🇩🇯',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Dominica',
      isoCode: 'DM',
      dialCode: '1',
      flagEmoji: '🇩🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Dominican Republic',
      isoCode: 'DO',
      dialCode: '1',
      flagEmoji: '🇩🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Ecuador',
      isoCode: 'EC',
      dialCode: '593',
      flagEmoji: '🇪🇨',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Egypt',
      isoCode: 'EG',
      dialCode: '20',
      flagEmoji: '🇪🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'El Salvador',
      isoCode: 'SV',
      dialCode: '503',
      flagEmoji: '🇸🇻',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Equatorial Guinea',
      isoCode: 'GQ',
      dialCode: '240',
      flagEmoji: '🇬🇶',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Eritrea',
      isoCode: 'ER',
      dialCode: '291',
      flagEmoji: '🇪🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Estonia',
      isoCode: 'EE',
      dialCode: '372',
      flagEmoji: '🇪🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Eswatini',
      isoCode: 'SZ',
      dialCode: '268',
      flagEmoji: '🇸🇿',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Ethiopia',
      isoCode: 'ET',
      dialCode: '251',
      flagEmoji: '🇪🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Falkland Islands',
      isoCode: 'FK',
      dialCode: '500',
      flagEmoji: '🇫🇰',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Faroe Islands',
      isoCode: 'FO',
      dialCode: '298',
      flagEmoji: '🇫🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Fiji Islands',
      isoCode: 'FJ',
      dialCode: '679',
      flagEmoji: '🇫🇯',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Finland',
      isoCode: 'FI',
      dialCode: '358',
      flagEmoji: '🇫🇮',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'France',
      isoCode: 'FR',
      dialCode: '33',
      flagEmoji: '🇫🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'French Guiana',
      isoCode: 'GF',
      dialCode: '594',
      flagEmoji: '🇬🇫',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'French Polynesia',
      isoCode: 'PF',
      dialCode: '689',
      flagEmoji: '🇵🇫',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'French Southern Territories',
      isoCode: 'TF',
      dialCode: '262',
      flagEmoji: '🇹🇫',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Gabon',
      isoCode: 'GA',
      dialCode: '241',
      flagEmoji: '🇬🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Georgia',
      isoCode: 'GE',
      dialCode: '995',
      flagEmoji: '🇬🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Germany',
      isoCode: 'DE',
      dialCode: '49',
      flagEmoji: '🇩🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Ghana',
      isoCode: 'GH',
      dialCode: '233',
      flagEmoji: '🇬🇭',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Gibraltar',
      isoCode: 'GI',
      dialCode: '350',
      flagEmoji: '🇬🇮',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Greece',
      isoCode: 'GR',
      dialCode: '30',
      flagEmoji: '🇬🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Greenland',
      isoCode: 'GL',
      dialCode: '299',
      flagEmoji: '🇬🇱',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Grenada',
      isoCode: 'GD',
      dialCode: '1',
      flagEmoji: '🇬🇩',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Guadeloupe',
      isoCode: 'GP',
      dialCode: '590',
      flagEmoji: '🇬🇵',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Guam',
      isoCode: 'GU',
      dialCode: '1',
      flagEmoji: '🇬🇺',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Guatemala',
      isoCode: 'GT',
      dialCode: '502',
      flagEmoji: '🇬🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Guernsey',
      isoCode: 'GG',
      dialCode: '44',
      flagEmoji: '🇬🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Guinea',
      isoCode: 'GN',
      dialCode: '224',
      flagEmoji: '🇬🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Guinea-Bissau',
      isoCode: 'GW',
      dialCode: '245',
      flagEmoji: '🇬🇼',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Guyana',
      isoCode: 'GY',
      dialCode: '592',
      flagEmoji: '🇬🇾',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Haiti',
      isoCode: 'HT',
      dialCode: '509',
      flagEmoji: '🇭🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Heard Island and McDonald Islands',
      isoCode: 'HM',
      dialCode: '672',
      flagEmoji: '🇭🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Honduras',
      isoCode: 'HN',
      dialCode: '504',
      flagEmoji: '🇭🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Hong Kong S.A.R.',
      isoCode: 'HK',
      dialCode: '852',
      flagEmoji: '🇭🇰',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Hungary',
      isoCode: 'HU',
      dialCode: '36',
      flagEmoji: '🇭🇺',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Iceland',
      isoCode: 'IS',
      dialCode: '354',
      flagEmoji: '🇮🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'India',
      isoCode: 'IN',
      dialCode: '91',
      flagEmoji: '🇮🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Indonesia',
      isoCode: 'ID',
      dialCode: '62',
      flagEmoji: '🇮🇩',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Iran',
      isoCode: 'IR',
      dialCode: '98',
      flagEmoji: '🇮🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Iraq',
      isoCode: 'IQ',
      dialCode: '964',
      flagEmoji: '🇮🇶',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Ireland',
      isoCode: 'IE',
      dialCode: '353',
      flagEmoji: '🇮🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Israel',
      isoCode: 'IL',
      dialCode: '972',
      flagEmoji: '🇮🇱',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Italy',
      isoCode: 'IT',
      dialCode: '39',
      flagEmoji: '🇮🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Ivory Coast',
      isoCode: 'CI',
      dialCode: '225',
      flagEmoji: '🇨🇮',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Jamaica',
      isoCode: 'JM',
      dialCode: '1',
      flagEmoji: '🇯🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Japan',
      isoCode: 'JP',
      dialCode: '81',
      flagEmoji: '🇯🇵',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Jersey',
      isoCode: 'JE',
      dialCode: '44',
      flagEmoji: '🇯🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Jordan',
      isoCode: 'JO',
      dialCode: '962',
      flagEmoji: '🇯🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Kazakhstan',
      isoCode: 'KZ',
      dialCode: '7',
      flagEmoji: '🇰🇿',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Kenya',
      isoCode: 'KE',
      dialCode: '254',
      flagEmoji: '🇰🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Kiribati',
      isoCode: 'KI',
      dialCode: '686',
      flagEmoji: '🇰🇮',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Kosovo',
      isoCode: 'XK',
      dialCode: '383',
      flagEmoji: '🇽🇰',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Kuwait',
      isoCode: 'KW',
      dialCode: '965',
      flagEmoji: '🇰🇼',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Kyrgyzstan',
      isoCode: 'KG',
      dialCode: '996',
      flagEmoji: '🇰🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Laos',
      isoCode: 'LA',
      dialCode: '856',
      flagEmoji: '🇱🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Latvia',
      isoCode: 'LV',
      dialCode: '371',
      flagEmoji: '🇱🇻',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Lebanon',
      isoCode: 'LB',
      dialCode: '961',
      flagEmoji: '🇱🇧',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Lesotho',
      isoCode: 'LS',
      dialCode: '266',
      flagEmoji: '🇱🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Liberia',
      isoCode: 'LR',
      dialCode: '231',
      flagEmoji: '🇱🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Libya',
      isoCode: 'LY',
      dialCode: '218',
      flagEmoji: '🇱🇾',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Liechtenstein',
      isoCode: 'LI',
      dialCode: '423',
      flagEmoji: '🇱🇮',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Lithuania',
      isoCode: 'LT',
      dialCode: '370',
      flagEmoji: '🇱🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Luxembourg',
      isoCode: 'LU',
      dialCode: '352',
      flagEmoji: '🇱🇺',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Macau S.A.R.',
      isoCode: 'MO',
      dialCode: '853',
      flagEmoji: '🇲🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Madagascar',
      isoCode: 'MG',
      dialCode: '261',
      flagEmoji: '🇲🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Malawi',
      isoCode: 'MW',
      dialCode: '265',
      flagEmoji: '🇲🇼',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Malaysia',
      isoCode: 'MY',
      dialCode: '60',
      flagEmoji: '🇲🇾',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Maldives',
      isoCode: 'MV',
      dialCode: '960',
      flagEmoji: '🇲🇻',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Mali',
      isoCode: 'ML',
      dialCode: '223',
      flagEmoji: '🇲🇱',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Malta',
      isoCode: 'MT',
      dialCode: '356',
      flagEmoji: '🇲🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Man (Isle of)',
      isoCode: 'IM',
      dialCode: '44',
      flagEmoji: '🇮🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Marshall Islands',
      isoCode: 'MH',
      dialCode: '692',
      flagEmoji: '🇲🇭',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Martinique',
      isoCode: 'MQ',
      dialCode: '596',
      flagEmoji: '🇲🇶',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Mauritania',
      isoCode: 'MR',
      dialCode: '222',
      flagEmoji: '🇲🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Mauritius',
      isoCode: 'MU',
      dialCode: '230',
      flagEmoji: '🇲🇺',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Mayotte',
      isoCode: 'YT',
      dialCode: '262',
      flagEmoji: '🇾🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Mexico',
      isoCode: 'MX',
      dialCode: '52',
      flagEmoji: '🇲🇽',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Micronesia',
      isoCode: 'FM',
      dialCode: '691',
      flagEmoji: '🇫🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Moldova',
      isoCode: 'MD',
      dialCode: '373',
      flagEmoji: '🇲🇩',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Monaco',
      isoCode: 'MC',
      dialCode: '377',
      flagEmoji: '🇲🇨',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Mongolia',
      isoCode: 'MN',
      dialCode: '976',
      flagEmoji: '🇲🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Montenegro',
      isoCode: 'ME',
      dialCode: '382',
      flagEmoji: '🇲🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Montserrat',
      isoCode: 'MS',
      dialCode: '1',
      flagEmoji: '🇲🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Morocco',
      isoCode: 'MA',
      dialCode: '212',
      flagEmoji: '🇲🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Mozambique',
      isoCode: 'MZ',
      dialCode: '258',
      flagEmoji: '🇲🇿',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Myanmar',
      isoCode: 'MM',
      dialCode: '95',
      flagEmoji: '🇲🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Namibia',
      isoCode: 'NA',
      dialCode: '264',
      flagEmoji: '🇳🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Nauru',
      isoCode: 'NR',
      dialCode: '674',
      flagEmoji: '🇳🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Nepal',
      isoCode: 'NP',
      dialCode: '977',
      flagEmoji: '🇳🇵',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Netherlands',
      isoCode: 'NL',
      dialCode: '31',
      flagEmoji: '🇳🇱',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'New Caledonia',
      isoCode: 'NC',
      dialCode: '687',
      flagEmoji: '🇳🇨',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'New Zealand',
      isoCode: 'NZ',
      dialCode: '64',
      flagEmoji: '🇳🇿',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Nicaragua',
      isoCode: 'NI',
      dialCode: '505',
      flagEmoji: '🇳🇮',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Niger',
      isoCode: 'NE',
      dialCode: '227',
      flagEmoji: '🇳🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Nigeria',
      isoCode: 'NG',
      dialCode: '234',
      flagEmoji: '🇳🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Niue',
      isoCode: 'NU',
      dialCode: '683',
      flagEmoji: '🇳🇺',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Norfolk Island',
      isoCode: 'NF',
      dialCode: '672',
      flagEmoji: '🇳🇫',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'North Korea',
      isoCode: 'KP',
      dialCode: '850',
      flagEmoji: '🇰🇵',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'North Macedonia',
      isoCode: 'MK',
      dialCode: '389',
      flagEmoji: '🇲🇰',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Northern Mariana Islands',
      isoCode: 'MP',
      dialCode: '1',
      flagEmoji: '🇲🇵',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Norway',
      isoCode: 'NO',
      dialCode: '47',
      flagEmoji: '🇳🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Oman',
      isoCode: 'OM',
      dialCode: '968',
      flagEmoji: '🇴🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Pakistan',
      isoCode: 'PK',
      dialCode: '92',
      flagEmoji: '🇵🇰',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Palau',
      isoCode: 'PW',
      dialCode: '680',
      flagEmoji: '🇵🇼',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Palestinian Territory Occupied',
      isoCode: 'PS',
      dialCode: '970',
      flagEmoji: '🇵🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Panama',
      isoCode: 'PA',
      dialCode: '507',
      flagEmoji: '🇵🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Papua New Guinea',
      isoCode: 'PG',
      dialCode: '675',
      flagEmoji: '🇵🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Paraguay',
      isoCode: 'PY',
      dialCode: '595',
      flagEmoji: '🇵🇾',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Peru',
      isoCode: 'PE',
      dialCode: '51',
      flagEmoji: '🇵🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Philippines',
      isoCode: 'PH',
      dialCode: '63',
      flagEmoji: '🇵🇭',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Pitcairn Island',
      isoCode: 'PN',
      dialCode: '870',
      flagEmoji: '🇵🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Poland',
      isoCode: 'PL',
      dialCode: '48',
      flagEmoji: '🇵🇱',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Portugal',
      isoCode: 'PT',
      dialCode: '351',
      flagEmoji: '🇵🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Puerto Rico',
      isoCode: 'PR',
      dialCode: '1',
      flagEmoji: '🇵🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Qatar',
      isoCode: 'QA',
      dialCode: '974',
      flagEmoji: '🇶🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Reunion',
      isoCode: 'RE',
      dialCode: '262',
      flagEmoji: '🇷🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Romania',
      isoCode: 'RO',
      dialCode: '40',
      flagEmoji: '🇷🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Russia',
      isoCode: 'RU',
      dialCode: '7',
      flagEmoji: '🇷🇺',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Rwanda',
      isoCode: 'RW',
      dialCode: '250',
      flagEmoji: '🇷🇼',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Saint Helena',
      isoCode: 'SH',
      dialCode: '290',
      flagEmoji: '🇸🇭',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Saint Kitts and Nevis',
      isoCode: 'KN',
      dialCode: '1',
      flagEmoji: '🇰🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Saint Lucia',
      isoCode: 'LC',
      dialCode: '1',
      flagEmoji: '🇱🇨',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Saint Pierre and Miquelon',
      isoCode: 'PM',
      dialCode: '508',
      flagEmoji: '🇵🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Saint Vincent and the Grenadines',
      isoCode: 'VC',
      dialCode: '1',
      flagEmoji: '🇻🇨',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Saint-Barthelemy',
      isoCode: 'BL',
      dialCode: '590',
      flagEmoji: '🇧🇱',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Saint-Martin (French part)',
      isoCode: 'MF',
      dialCode: '590',
      flagEmoji: '🇲🇫',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Samoa',
      isoCode: 'WS',
      dialCode: '685',
      flagEmoji: '🇼🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'San Marino',
      isoCode: 'SM',
      dialCode: '378',
      flagEmoji: '🇸🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Sao Tome and Principe',
      isoCode: 'ST',
      dialCode: '239',
      flagEmoji: '🇸🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Saudi Arabia',
      isoCode: 'SA',
      dialCode: '966',
      flagEmoji: '🇸🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Senegal',
      isoCode: 'SN',
      dialCode: '221',
      flagEmoji: '🇸🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Serbia',
      isoCode: 'RS',
      dialCode: '381',
      flagEmoji: '🇷🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Seychelles',
      isoCode: 'SC',
      dialCode: '248',
      flagEmoji: '🇸🇨',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Sierra Leone',
      isoCode: 'SL',
      dialCode: '232',
      flagEmoji: '🇸🇱',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Singapore',
      isoCode: 'SG',
      dialCode: '65',
      flagEmoji: '🇸🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Sint Maarten (Dutch part)',
      isoCode: 'SX',
      dialCode: '1721',
      flagEmoji: '🇸🇽',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Slovakia',
      isoCode: 'SK',
      dialCode: '421',
      flagEmoji: '🇸🇰',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Slovenia',
      isoCode: 'SI',
      dialCode: '386',
      flagEmoji: '🇸🇮',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Solomon Islands',
      isoCode: 'SB',
      dialCode: '677',
      flagEmoji: '🇸🇧',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Somalia',
      isoCode: 'SO',
      dialCode: '252',
      flagEmoji: '🇸🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'South Africa',
      isoCode: 'ZA',
      dialCode: '27',
      flagEmoji: '🇿🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'South Georgia',
      isoCode: 'GS',
      dialCode: '500',
      flagEmoji: '🇬🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'South Korea',
      isoCode: 'KR',
      dialCode: '82',
      flagEmoji: '🇰🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'South Sudan',
      isoCode: 'SS',
      dialCode: '211',
      flagEmoji: '🇸🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Spain',
      isoCode: 'ES',
      dialCode: '34',
      flagEmoji: '🇪🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Sri Lanka',
      isoCode: 'LK',
      dialCode: '94',
      flagEmoji: '🇱🇰',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Sudan',
      isoCode: 'SD',
      dialCode: '249',
      flagEmoji: '🇸🇩',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Suriname',
      isoCode: 'SR',
      dialCode: '597',
      flagEmoji: '🇸🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Svalbard and Jan Mayen Islands',
      isoCode: 'SJ',
      dialCode: '47',
      flagEmoji: '🇸🇯',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Sweden',
      isoCode: 'SE',
      dialCode: '46',
      flagEmoji: '🇸🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Switzerland',
      isoCode: 'CH',
      dialCode: '41',
      flagEmoji: '🇨🇭',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Syria',
      isoCode: 'SY',
      dialCode: '963',
      flagEmoji: '🇸🇾',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Taiwan',
      isoCode: 'TW',
      dialCode: '886',
      flagEmoji: '🇹🇼',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Tajikistan',
      isoCode: 'TJ',
      dialCode: '992',
      flagEmoji: '🇹🇯',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Tanzania',
      isoCode: 'TZ',
      dialCode: '255',
      flagEmoji: '🇹🇿',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Thailand',
      isoCode: 'TH',
      dialCode: '66',
      flagEmoji: '🇹🇭',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'The Bahamas',
      isoCode: 'BS',
      dialCode: '1',
      flagEmoji: '🇧🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'The Gambia',
      isoCode: 'GM',
      dialCode: '220',
      flagEmoji: '🇬🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Timor-Leste',
      isoCode: 'TL',
      dialCode: '670',
      flagEmoji: '🇹🇱',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Togo',
      isoCode: 'TG',
      dialCode: '228',
      flagEmoji: '🇹🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Tokelau',
      isoCode: 'TK',
      dialCode: '690',
      flagEmoji: '🇹🇰',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Tonga',
      isoCode: 'TO',
      dialCode: '676',
      flagEmoji: '🇹🇴',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Trinidad and Tobago',
      isoCode: 'TT',
      dialCode: '1',
      flagEmoji: '🇹🇹',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Tunisia',
      isoCode: 'TN',
      dialCode: '216',
      flagEmoji: '🇹🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Turkey',
      isoCode: 'TR',
      dialCode: '90',
      flagEmoji: '🇹🇷',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Turkmenistan',
      isoCode: 'TM',
      dialCode: '993',
      flagEmoji: '🇹🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Turks and Caicos Islands',
      isoCode: 'TC',
      dialCode: '1',
      flagEmoji: '🇹🇨',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Tuvalu',
      isoCode: 'TV',
      dialCode: '688',
      flagEmoji: '🇹🇻',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Uganda',
      isoCode: 'UG',
      dialCode: '256',
      flagEmoji: '🇺🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Ukraine',
      isoCode: 'UA',
      dialCode: '380',
      flagEmoji: '🇺🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'United Arab Emirates',
      isoCode: 'AE',
      dialCode: '971',
      flagEmoji: '🇦🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'United Kingdom',
      isoCode: 'GB',
      dialCode: '44',
      flagEmoji: '🇬🇧',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'United States',
      isoCode: 'US',
      dialCode: '1',
      flagEmoji: '🇺🇸',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'United States Minor Outlying Islands',
      isoCode: 'UM',
      dialCode: '1',
      flagEmoji: '🇺🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Uruguay',
      isoCode: 'UY',
      dialCode: '598',
      flagEmoji: '🇺🇾',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Uzbekistan',
      isoCode: 'UZ',
      dialCode: '998',
      flagEmoji: '🇺🇿',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Vanuatu',
      isoCode: 'VU',
      dialCode: '678',
      flagEmoji: '🇻🇺',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Vatican City State (Holy See)',
      isoCode: 'VA',
      dialCode: '379',
      flagEmoji: '🇻🇦',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Venezuela',
      isoCode: 'VE',
      dialCode: '58',
      flagEmoji: '🇻🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Vietnam',
      isoCode: 'VN',
      dialCode: '84',
      flagEmoji: '🇻🇳',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Virgin Islands (British)',
      isoCode: 'VG',
      dialCode: '1',
      flagEmoji: '🇻🇬',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Virgin Islands (US)',
      isoCode: 'VI',
      dialCode: '1',
      flagEmoji: '🇻🇮',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Wallis and Futuna Islands',
      isoCode: 'WF',
      dialCode: '681',
      flagEmoji: '🇼🇫',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Western Sahara',
      isoCode: 'EH',
      dialCode: '212',
      flagEmoji: '🇪🇭',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Yemen',
      isoCode: 'YE',
      dialCode: '967',
      flagEmoji: '🇾🇪',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Zambia',
      isoCode: 'ZM',
      dialCode: '260',
      flagEmoji: '🇿🇲',
      phoneHint: defaultPhoneHint,
    ),
    CountryCode(
      name: 'Zimbabwe',
      isoCode: 'ZW',
      dialCode: '263',
      flagEmoji: '🇿🇼',
      phoneHint: defaultPhoneHint,
    ),
  ];
}
